# Generated by Django 3.1.12 on 2021-10-14 15:33

from django.db import migrations, models
import djongo.models.fields
import pnl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('companyId', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('data', djongo.models.fields.EmbeddedField(model_container=pnl.models.QokoonInput)),
                ('meta', djongo.models.fields.EmbeddedField(model_container=pnl.models.CompanyMeta)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
