class Constants:
    TOTAL_SG_AND_A = "TOTAL_SG_AND_A"
    NET_INCOME = "NET_INCOME"
    GROSS_PROFIT = "GROSS_PROFIT"
    COST_OF_SALES = "COST_OF_SALES"
    EBITDA = "EBITDA"
    TOTAL_SALES = "TOTAL_SALES"