services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
    ports:
      - 27017:27017

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mongodb